# 1. Math in deep learning

## Table creation

In [31]:
import numpy

length = 3

table1d = numpy.array([i for i in range(length)])
table2d = numpy.array([
    [ i * length + j for j in range(length)]
     for i in range(length)])
table3d = numpy.array([
    [ 
        [i * length**2 + j * length + k for k in range(length)]
        for j in range(length)
    ]
    for i in range(length)
])

table1d, table2d, table3d

(array([0, 1, 2]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]))

## Fields/methods of `numpy.array()`

In [30]:
table1d.dtype, table2d.dtype, table3d.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [28]:
table1d.ndim, table2d.ndim, table3d.ndim

(1, 2, 3)

In [29]:
table1d.shape, table2d.shape, table3d.shape

((3,), (3, 3), (3, 3, 3))

In [32]:
type(table1d), type(table2d), type(table3d)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Operations on tensors

In [51]:
_array0 = [[0, 10, 20, 30],
           [40, 50, 60, 70]]
_array1 = [[1, 11, 21, 31],
           [41, 51, 61, 71]]
_array2 = [[2, 12, 22, 32],
           [42, 52, 62, 72]]

tensor = numpy.array([_array0, _array1,_array2])
print(tensor.shape)
tensor

(3, 2, 4)


array([[[ 0, 10, 20, 30],
        [40, 50, 60, 70]],

       [[ 1, 11, 21, 31],
        [41, 51, 61, 71]],

       [[ 2, 12, 22, 32],
        [42, 52, 62, 72]]])

### Slicing

In [45]:
tensor[0, :, :], tensor[1, :, :], tensor[2, :, :]

(array([[ 0, 10, 20, 30],
        [40, 50, 60, 70]]),
 array([[ 1, 11, 21, 31],
        [41, 51, 61, 71]]),
 array([[ 2, 12, 22, 32],
        [42, 52, 62, 72]]))

In [47]:
tensor[:, 0, :], tensor[:, 1, :]

(array([[ 0, 10, 20, 30],
        [ 1, 11, 21, 31],
        [ 2, 12, 22, 32]]),
 array([[40, 50, 60, 70],
        [41, 51, 61, 71],
        [42, 52, 62, 72]]))

In [42]:
tensor[:, :, 0], tensor[:, :, 1], tensor[:, :, 2], tensor[:, :, 3]

(array([[ 0, 40],
        [ 1, 41],
        [ 2, 42]]),
 array([[10, 50],
        [11, 51],
        [12, 52]]),
 array([[20, 60],
        [21, 61],
        [22, 62]]),
 array([[30, 70],
        [31, 71],
        [32, 72]]))

### Reshape

In [49]:
tensor.reshape(4, 3, 2)

array([[[ 0, 10],
        [20, 30],
        [40, 50]],

       [[60, 70],
        [ 1, 11],
        [21, 31]],

       [[41, 51],
        [61, 71],
        [ 2, 12]],

       [[22, 32],
        [42, 52],
        [62, 72]]])

In [50]:
tensor.reshape(4, 2, 3)

array([[[ 0, 10, 20],
        [30, 40, 50]],

       [[60, 70,  1],
        [11, 21, 31]],

       [[41, 51, 61],
        [71,  2, 12]],

       [[22, 32, 42],
        [52, 62, 72]]])

### Broadcasting

In [54]:
a = numpy.array([[ 0,  0,  0],
                 [10, 10, 10],
                 [20, 20, 20],
                 [30, 30, 30]])
b = numpy.array([1, 2, 3])

In [55]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [56]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [59]:
c = numpy.array([0, 10, 20, 30])
d = numpy.array([1, 2, 3])

In [60]:
c + d

ValueError: operands could not be broadcast together with shapes (4,) (3,) 